=== microsoft/azure-tools-for-java/PluginsAndFeatures/azure-toolkit-for-intellij/azure-intellij-plugin-guideline/src/main/resources/schema/Sequence.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Guidance",
  "description": "****",
  "type": "object",
  "required": [
    "title",
    "description",
    "repository",
    "phases"
  ],
  "properties": {
    "name": {
      "description": "The deployment name",
      "type": "string"
    },
    "title": {
      "description": "Display title of this guidance",
      "type": "string"
    },
    "description": {
      "description": "Description message for this course",
      "type": "string"
    },
    "repository": {
      "description": "Git repository of the project to be used in this course",
      "type": "string",
      "format": "uri"
    },
    "context": {
      "description": "shared data context among phases and steps, you can config default values here",
      "type": "object",
      "default": {}
    },
    "phases": {
      "description": "phases of this guidance",
      "type": "array",
      "items": { "$ref": "Phase.json" },
      "minItems": 1,
      "uniqueItems": true
    }
  }
}

=== microsoft/azure-tools-for-java/PluginsAndFeatures/azure-toolkit-for-intellij/azure-intellij-plugin-guideline/src/main/resources/schema/example.json
{
  "$schema": "Sequence.json",
  "name": "hello-webapp",
  "title": "Deploy Your First Web App to Azure",
  "description": "Sample project for Azure Web App with Application Insights resource connection. By running the sample, you will have an example of deploying project to Azure Web App.",
  "repository": "https://github.com/spring-guides/gs-spring-boot.git",
  "context": {
    "subscriptionId": "",
    "accountConfig": {
      "$ref": "AccountConfig.json"
    },
    "webAppConfig": {
      "$ref": "WebAppConfig.json"
    }
  },
  "phases": [
    {
      "title": "Sign-in",
      "description": "Sign in with your Azure account",
      "steps": [
        {
          "title": "Sign-in",
          "description": null,
          "task": {
            "name": "task.signin",
            "paramMapping": {
              "accountConfig": "context.accountConfig"
            }
          }
        },
        {
          "title": "Select Subscription",
          "description": null,
          "task": {
            "name": "task.select_subscription",
            "resultMapping": {
              "subscriptionId": "context.subscriptionId"
            }
          }
        }
      ]
    },
    {
      "title": "Prepare",
      "description": "Prepare dependent resources",
      "help": "./resources/aa_bb",
      "steps": [
        {
          "title": "Create web app",
          "description": null,
          "input": {
            "name": "input.webapp.name",
            "paramMapping": {
              "subscriptionId": "context.subscriptionId"
            },
            "resultMapping": {
              "webappName": "context.webAppConfig.name"
            }
          },
          "task": {
            "name": "task.webapp.create",
            "paramMapping": {
              "webAppConfig": "context.webAppConfig"
            }
          }
        },
        {
          "title": "Create application insight app",
          "description": null,
          "task": {
            "name": "task.application_insights.create"
          }
        }
      ]
    },
    {
      "title": "Build & Deploy",
      "description": "Build artifacts, prepare dependent resources and deploy to Azure Web App",
      "steps": [
        {
          "title": "Build Artifact",
          "description": null,
          "task": {
            "name": "task.webapp.build"
          }
        },
        {
          "title": "Deploy",
          "description": "Deploy to Azure Web App ${context.webapp.name}",
          "task": {
            "name": "task.webapp.deploy"
          }
        }
      ]
    },
    {
      "title": "Done",
      "type": "summary",
      "description": "Your project has been deployed to Aure Web App, enjoy your Azure experience!",
      "steps": [
        {
          "title": "open your web app in browser",
          "description": null,
          "task": {
            "name": "task.resource.open_in_portal"
          }
        },
        {
          "title": "clean up resources",
          "description": null,
          "task": {
            "name": "task.resource.clean_up"
          }
        }
      ]
    }
  ]
}
